// Fuente: Plan_MarcoMeschini.pdf y Alimentacion_MarcoMeschini.pdf (Agustín Paz, @aguspazfit). Mes 1.
// descanso en segundos (0 = sin descanso). aprox = series de aproximación (no cuentan). video = id de Google Drive.
const HIIT = { titulo: 'Cardio HIIT — post entrenamiento', sub: '3 vueltas · 1 min 30 seg de descanso entre vueltas', pasos: [
  { nombre: 'Burpees', nota: 'Plancha completa, subís y saltás palmeando arriba.', dosis: '8 reps' },
  { nombre: 'Angelitos / jumping jacks', nota: 'Brazos y piernas coordinados. Ritmo máximo.', dosis: '40 seg' },
  { nombre: 'Sentadillas con salto', nota: 'Rodillas al pecho. Aterrizás suave y semiflexionado.', dosis: '20 reps' },
  { nombre: 'Mountain climbers', nota: 'Desde plancha alta. Rodillas al pecho alternando.', dosis: '30 seg' },
] };

window.DATA = {
  plan: { mes: 1, dias: [
    { id: 'lun', dia: 1, titulo: 'Torso completo', bloques: [
      { aprox: 2, series: 3, reps: '10 - 8 - 6 subiendo el peso', descanso: 90, badges: ['APROX'],
        ejercicios: [{ nombre: 'Pect deck', nota: '2 series de aproximación (5 y 3 reps) con peso ligero + 3 efectivas.', video: '1sYMlhKOOZZdZc4qABt5ywxXvQhYpepGj' }] },
      { series: 3, reps: '20 - 15 - 12 · dropset y fallo en la última', descanso: 90, badges: ['DROPSET', 'FALLO'],
        ejercicios: [{ nombre: 'Pullover con polea soga', nota: 'Mantener 2 seg arriba y 2 seg abajo.', video: '1YBeCt9UwF80RYhNFNNsytD44LB6BjhXH' }] },
      { aprox: 2, series: 2, reps: '10 - 6 · dropset y fallo en la última', descanso: 120, badges: ['APROX', 'DROPSET', 'FALLO'],
        ejercicios: [{ nombre: 'Press inclinado con mancuernas', nota: '2 series de aproximación (3 y 2 reps) con peso ligero + 2 efectivas.', video: '1Inz38000Wa_oKI9ovOB2X5SobloBPMT4' }] },
      { series: 2, reps: '10 - 6', descanso: 90, badges: [],
        ejercicios: [{ nombre: 'Jalón en dorsalera agarre unilateral neutro', nota: 'Inclinarse hacia el lado contrayendo los oblicuos.', video: '1oR58_IRjLuhFJA9Y-C3Mm-4K3bBwiIK1' }] },
      { series: 3, reps: '10 - 8 - 6 subiendo el peso', descanso: 90, badges: [],
        ejercicios: [{ nombre: 'Press de hombros con mancuernas sentado', video: '1lFEraIA3AcWH9zHcrOq1A_JoTnjOUWLv' }] },
      { series: 3, reps: '15 - 10 - 8 en ambos, subiendo el peso', descanso: 60, badges: ['BISERIE'],
        ejercicios: [{ nombre: 'Press plano en máquina con placas' }, { nombre: 'Curl de bíceps martillo en simultáneo con mancuernas', video: '1mUnTrondsdWRE0WXGyupH9yacUbqMjuK' }] },
      { series: 3, reps: '12 - 8 - 6 en ambos · dropset y fallo en la última de remo', descanso: 60, badges: ['BISERIE', 'DROPSET', 'FALLO'],
        ejercicios: [{ nombre: 'Remo Gironda en máquina', video: '12byDyN3ASYpx2dyWCTNOYu3Dxne9-ZZx' }, { nombre: 'Extensión de tríceps trasnuca con mancuerna a 2 manos' }] },
      { series: 2, reps: '15 - 10 en ambos · dropset y fallo x2 en la última de curl', descanso: 60, badges: ['BISERIE', 'DROPSET', 'FALLO'],
        ejercicios: [{ nombre: 'Extensión de tríceps unilateral en polea con manopla', video: '1K_QU1YffvcuzwmhrrsWS5dbjBrPSJIFA' }, { nombre: 'Curl de bíceps con polea barra', video: '1FuIr0YTlL0mRv9NrkZAZnIYtCBu7TaMp' }] },
      { series: 3, reps: '8 - fallo - fallo · triple dropset', descanso: 60, badges: ['DROPSET', 'FALLO'],
        ejercicios: [{ nombre: 'Vuelos laterales con mancuernas sentado', nota: 'Triple dropset. 3 series de 8 reps y fallo.', video: '19bX9TLAWEd6avohJQVJyLLNqlSiRp81p' }] },
      { series: 3, reps: '20 - 15 - 12 en ambos, subiendo el peso', descanso: 60, badges: ['BISERIE'],
        ejercicios: [{ nombre: 'Vuelos posteriores en pect deck', video: '1E809RsvQoE6gSJDHEdwrihya_aBQs5ne' }, { nombre: 'Curl de bíceps supino en simultáneo sentado en banco, codos rígidos', video: '1iUwLfPv09ZQb6fV0lX_EasJ4m-fk20Nz' }] },
    ], cardio: HIIT },

    { id: 'mar', dia: 2, titulo: 'Piernas completo', bloques: [
      { series: 3, reps: '20 - 15 - 10 subiendo el peso', descanso: 120, badges: [],
        ejercicios: [{ nombre: 'Extensión de cuádriceps', nota: 'Las primeras 2 series cuentan como calentamiento efectivo.', video: '18vYJAYCpYwRl8sUU-8PYzKGQmi-2LMD9' }] },
      { aprox: 2, series: 3, reps: '12 - 8 - 6 subiendo el peso', descanso: 150, badges: ['APROX'],
        ejercicios: [{ nombre: 'Sentadilla en Smith', nota: '2 series de aproximación (5 y 3 reps) con peso ligero + 3 efectivas.', video: '1WQr-FBtumZg8QLTtn8xT5PNp6yXN-QU8' }] },
      { series: 3, reps: '12 - 8 - 6 en prensa · estocadas al fallo (mín. 12 c/lado)', descanso: 90, badges: ['BISERIE', 'FALLO'],
        ejercicios: [{ nombre: 'Prensa pies anchos', video: '1ULzO9uPU7EtOR0L9WY7-lN-Ri28qPgc1' }, { nombre: 'Estocadas caminando ida y vuelta al fallo', nota: 'Mínimo 12 por lado.' }] },
      { series: 3, reps: '12 - 10 - 8 en ambos', descanso: 90, badges: ['BISERIE'],
        ejercicios: [{ nombre: 'Curl femoral unilateral parado o acostado', video: '1YZ9t3shIZrHE1evZAtlVPJ9nCelbjT6m' }, { nombre: 'Peso muerto rumano con mancuernas' }] },
      { series: 3, reps: '20 - 15 - 12 · dropset y fallo en la última de ambos', descanso: 90, badges: ['BISERIE', 'DROPSET', 'FALLO'],
        ejercicios: [{ nombre: 'Abductor en máquina' }, { nombre: 'Aductor en máquina', video: '1_X4IP_s7HObZ3BM_x9RgxaVxGBllVsCS' }] },
      { series: 3, reps: '20 - 15 - 12 · dropset y fallo en la última', descanso: 60, badges: ['DROPSET', 'FALLO'],
        ejercicios: [{ nombre: 'Elevación de gemelos en prensa', nota: 'Mantener 2 seg abajo al estirar.' }] },
    ], cardio: { titulo: 'Caminata en cinta con inclinación 10', sub: 'Post piernas · 20 minutos totales', pasos: [
      { nombre: '5 km/h', nota: 'Inclinación 10%. Ritmo suave de entrada.', dosis: '5 min' },
      { nombre: '6,5 km/h', nota: 'Inclinación 10%. Ritmo moderado.', dosis: '5 min' },
      { nombre: '5 km/h', nota: 'Inclinación 10%. Recuperación activa.', dosis: '5 min' },
      { nombre: '7 km/h', nota: 'Inclinación 10%. Esfuerzo final.', dosis: '5 min' },
    ] } },

    { id: 'mie', dia: 3, titulo: 'Torso', bloques: [
      { series: 3, reps: '15 - 10 - 6 subiendo el peso', descanso: 90, badges: [],
        ejercicios: [{ nombre: 'Aperturas con mancuernas inclinadas' }] },
      { series: 3, reps: '20 - 15 - 10', descanso: 60, badges: [],
        ejercicios: [{ nombre: 'Vuelos posteriores en pect deck', video: '1E809RsvQoE6gSJDHEdwrihya_aBQs5ne' }] },
      { series: 3, reps: '10 - 8 - 6 subiendo el peso', descanso: 90, badges: [],
        ejercicios: [{ nombre: 'Press inclinado en máquina Hammer' }] },
      { series: 3, reps: '10 - 6 - 4 subiendo el lastre', descanso: 120, badges: [],
        ejercicios: [{ nombre: 'Jalón en dorsalera agarre supino con lastre', nota: 'Mismo agarre que dominadas supinas. Con lastre.' }] },
      { series: 3, reps: '20 - 15 - 12 en ambos, subiendo el peso', descanso: 60, badges: ['BISERIE'],
        ejercicios: [{ nombre: 'Remo al mentón con barra Z' }, { nombre: 'Vuelos laterales con mancuernas parado', video: '19bX9TLAWEd6avohJQVJyLLNqlSiRp81p' }] },
      { series: 2, reps: 'Al fallo', descanso: 120, badges: ['FALLO'],
        ejercicios: [{ nombre: 'Jalón prono en dorsalera', nota: 'Mantener 10 seg abajo en la 1ra · hago 10 · mantener 5 · hago al fallo.', video: '1TXkbZEJBwWekdCiVwZLcj1Xb0434HkLS' }] },
      { series: 3, reps: '15 - 10 - 8 en ambos, subiendo el peso', descanso: 60, badges: ['BISERIE'],
        ejercicios: [{ nombre: 'Curl de bíceps supino con barra Z' }, { nombre: 'Press francés con barra Z' }] },
      { series: 2, reps: '12 - 8 en ambos · dropset y fallo en ambos en la última', descanso: 60, badges: ['BISERIE', 'DROPSET', 'FALLO'],
        ejercicios: [{ nombre: 'Curl de bíceps martillo con polea unilateral', video: '1H2lcAYguaJuwVbkq9t8tGGF6PPLSs_RJ' }, { nombre: 'Extensión de tríceps con polea soga', video: '1Rs5aHfVbXC5eq1DM4d5RBEYbN2OqiJZG' }] },
      { series: 2, reps: 'Al fallo', descanso: 60, badges: ['FALLO'],
        ejercicios: [{ nombre: 'Vuelos laterales alternos con mancuernas', nota: 'Mantengo izquierda arriba · hago 5 · viceversa · después ambos al fallo.', video: '1m4QCfp_nzwroJp5KETYAO8_3I3-aNRge' }] },
      { series: 1, reps: '15 - fallo - fallo · 40 seg de descanso entre rounds, sin bajar el peso', descanso: 0, badges: ['SERIE GIGANTE', 'FALLO'],
        ejercicios: [{ nombre: 'Cruces con polea baja — serie gigante', nota: '15 reps · descanso 40 seg · sin bajar el peso · fallo x3.', video: '1dmFo_AKoBk9LPL-tmN29PyExRwJosQwd' }] },
    ], cardio: { titulo: 'Pasadas en cinta', sub: '30 seg de descanso entre cada pasada', video: '1cR38DQeLNh0h7X0WGgueOL0AABqqGWp2', pasos: [
      { nombre: 'Trote continuo — 7 km/h', nota: 'Trote suave de activación.', dosis: '3 min' },
      { nombre: 'Trote rápido — 8 km/h', nota: 'Ritmo sostenido. Respiración controlada.', dosis: '1:30 min' },
      { nombre: 'Sprint ×2 — 10 km/h', nota: 'Velocidad alta. 30 seg de descanso entre cada una.', dosis: '40 seg c/u' },
      { nombre: 'Sprint ×2 — 11 km/h', nota: 'Mayor intensidad. 30 seg de descanso entre cada una.', dosis: '30 seg c/u' },
      { nombre: 'Sprint ×2 — 12 km/h', nota: 'Máximo sostenido. 30 seg de descanso entre cada una.', dosis: '30 seg c/u' },
      { nombre: 'Sprint ×2 — 13 km/h', nota: 'Al límite. 30 seg de descanso entre cada una.', dosis: '30 seg c/u' },
      { nombre: 'Sprint final — 14 km/h', nota: 'Dalo todo en la última.', dosis: '30 seg' },
    ] } },

    { id: 'vie', dia: 5, titulo: 'Torso + intensidad', bloques: [
      { series: 3, reps: '15 - 10 - 8 · dropset y fallo en la última', descanso: 120, badges: ['DROPSET', 'FALLO'],
        ejercicios: [{ nombre: 'Press de hombros militar en Smith' }] },
      { series: 3, reps: '15 - 10 - 6 · dropset y fallo en la última', descanso: 120, badges: ['DROPSET', 'FALLO'],
        ejercicios: [{ nombre: 'Press inclinado en Smith' }] },
      { series: 3, reps: '15 - 10 - 8 subiendo el peso', descanso: 90, badges: [],
        ejercicios: [{ nombre: 'Remo con barra agarre prono' }] },
      { series: 3, reps: 'Al fallo en ambos', descanso: 120, badges: ['BISERIE', 'FALLO'],
        ejercicios: [{ nombre: 'Jalón en dorsalera agarre neutro', video: '1aJuJQ0y9XVlgnPlIWxCrsfmWQNWeMMpK' }, { nombre: 'Jalón en dorsalera agarre prono', nota: 'En lugar de dominadas.', video: '1TXkbZEJBwWekdCiVwZLcj1Xb0434HkLS' }] },
      { series: 3, reps: '12 - 8 - 6 en ambos, subiendo el peso', descanso: 60, badges: ['BISERIE'],
        ejercicios: [{ nombre: 'Press plano con mancuernas', video: '1nAOrcg2VXFdfQ_plhsC7PDUS_kosp_VR' }, { nombre: 'Curl de bíceps sentado supino con mancuernas', video: '1iUwLfPv09ZQb6fV0lX_EasJ4m-fk20Nz' }] },
      { series: 2, reps: '12 - 8 en ambos, subiendo el peso', descanso: 90, badges: ['BISERIE'],
        ejercicios: [{ nombre: 'Remo en polea agarre supino con barra' }, { nombre: 'Fondos para tríceps con peso y pies sobre banco' }] },
      { series: 2, reps: '15 - 10 en ambos · dropset y fallo x2 en la última de curl', descanso: 60, badges: ['BISERIE', 'DROPSET', 'FALLO'],
        ejercicios: [{ nombre: 'Extensión de tríceps con polea a 1 mano manopla', video: '1K_QU1YffvcuzwmhrrsWS5dbjBrPSJIFA' }, { nombre: 'Curl de bíceps en polea barra agarre prono' }] },
      { series: 2, reps: '15 - 10 en ambos, subiendo el peso', descanso: 60, badges: ['BISERIE'],
        ejercicios: [{ nombre: 'Curl de bíceps en banco inclinado supino', video: '1LJ15BBVzDlk4gMozdUR6UwHM9JixFz7W' }, { nombre: 'Press francés con mancuernas en banco inclinado', video: '1aWfwf-hv0t-h6NW9xkb-3RR9-m2w1W0Q' }] },
      { series: 3, reps: '20 - 15 - 10 · dropset y fallo en la última', descanso: 60, badges: ['DROPSET', 'FALLO'],
        ejercicios: [{ nombre: 'Vuelos laterales a una mano con polea tobillera', nota: 'A la altura de las rodillas.', video: '13OHlzX9n5FKteNVSbf8-4u4JIwWiEH-o' }] },
      { series: 2, reps: 'Al fallo en todos', descanso: 90, badges: ['SUPERSERIE', 'FALLO'],
        ejercicios: [{ nombre: 'Face pull con polea soga', video: '1Qlrzk2tdOYiYdVamqR04zC6TQexcbJ3L' }, { nombre: 'Extensión trasnuca con polea soga', video: '1bsgBx3qN-tfK_VnNDwXMhn5q8XMV__ZU' }, { nombre: 'Curl martillo con polea soga', video: '1H2lcAYguaJuwVbkq9t8tGGF6PPLSs_RJ' }] },
      { series: 1, reps: 'Fallo diamantes → fallo anchas sin descanso', descanso: 0, badges: ['FALLO'],
        ejercicios: [{ nombre: 'Finisher — flexiones diamantes', nota: 'Al fallo · inmediatamente flexiones anchas al fallo sin descanso.' }] },
    ], cardio: HIIT },
  ] },

  videos: [
    { grupo: 'Abdominales', titulo: 'Crunch abdominal con piernas elevadas', id: '12SzEuicNeXrrQdkijze-KNy8HSWyTt3g' },
    { grupo: 'Abdominales', titulo: 'Crunch abdominal declinado', id: '1xM4enzGVqvyV2BCBy5TI6YJc2PzX2MGM' },
    { grupo: 'Abdominales', titulo: 'Crunch abdominal con piernas elevadas y disco', id: '1b5J2EbcthvXN7O6mYS6_LU24fEDhwb44' },
    { grupo: 'Abdominales', titulo: 'Elevación de piernas acostado', id: '1yN-mJJOazUtodL6QuKMAN7_dS8UXe9aU' },
    { grupo: 'Bíceps', titulo: 'Curl de bíceps inclinado', id: '1LJ15BBVzDlk4gMozdUR6UwHM9JixFz7W' },
    { grupo: 'Bíceps', titulo: 'Curl de bíceps martillo', id: '1mUnTrondsdWRE0WXGyupH9yacUbqMjuK' },
    { grupo: 'Bíceps', titulo: 'Curl de bíceps martillo unilateral en polea', id: '1H2lcAYguaJuwVbkq9t8tGGF6PPLSs_RJ' },
    { grupo: 'Bíceps', titulo: 'Curl de bíceps supino con alternación', id: '1L7aDg4RhcqPQEcmkfafkJ192Wv60uLGA' },
    { grupo: 'Bíceps', titulo: 'Curl de bíceps supino con polea', id: '1FuIr0YTlL0mRv9NrkZAZnIYtCBu7TaMp' },
    { grupo: 'Bíceps', titulo: 'Curl de bíceps supino sentado', id: '1iUwLfPv09ZQb6fV0lX_EasJ4m-fk20Nz' },
    { grupo: 'Hombros', titulo: 'Face pull', id: '1Qlrzk2tdOYiYdVamqR04zC6TQexcbJ3L' },
    { grupo: 'Hombros', titulo: 'Press de hombros con mancuernas', id: '1lFEraIA3AcWH9zHcrOq1A_JoTnjOUWLv' },
    { grupo: 'Hombros', titulo: 'Vuelos isométricos alternos', id: '1m4QCfp_nzwroJp5KETYAO8_3I3-aNRge' },
    { grupo: 'Hombros', titulo: 'Vuelos laterales con mancuernas', id: '19bX9TLAWEd6avohJQVJyLLNqlSiRp81p' },
    { grupo: 'Hombros', titulo: 'Vuelos laterales unilateral en polea', id: '13OHlzX9n5FKteNVSbf8-4u4JIwWiEH-o' },
    { grupo: 'Hombros', titulo: 'Vuelos posteriores con polea', id: '1uAoMJ9ahx5q_v5uLnl2BqS7FIOqrZa1s' },
    { grupo: 'Hombros', titulo: 'Vuelos posteriores en pect deck', id: '1E809RsvQoE6gSJDHEdwrihya_aBQs5ne' },
    { grupo: 'Piernas', titulo: 'Aductor en máquina', id: '1_X4IP_s7HObZ3BM_x9RgxaVxGBllVsCS' },
    { grupo: 'Piernas', titulo: 'Curl femoral en máquina', id: '1YZ9t3shIZrHE1evZAtlVPJ9nCelbjT6m' },
    { grupo: 'Piernas', titulo: 'Extensión de cuádriceps', id: '18vYJAYCpYwRl8sUU-8PYzKGQmi-2LMD9' },
    { grupo: 'Piernas', titulo: 'Goblet squat', id: '1GoMVCI0tXzHK-4EziKQa94jgZ2RTS8oX' },
    { grupo: 'Piernas', titulo: 'Hack squat', id: '1xEqhjRlS7zmNVUg8c3uhntvB8sHq_LK_' },
    { grupo: 'Piernas', titulo: 'Prensa', id: '1ULzO9uPU7EtOR0L9WY7-lN-Ri28qPgc1' },
    { grupo: 'Piernas', titulo: 'Sentadilla en Smith', id: '1WQr-FBtumZg8QLTtn8xT5PNp6yXN-QU8' },
    { grupo: 'Tríceps', titulo: 'Extensión de tríceps en polea barra', id: '1Y5wg7lrGj295FTbOIUZC1KI6fXK0iEXf' },
    { grupo: 'Tríceps', titulo: 'Extensión trasnuca en polea soga', id: '1bsgBx3qN-tfK_VnNDwXMhn5q8XMV__ZU' },
    { grupo: 'Tríceps', titulo: 'Extensión de tríceps soga', id: '1Rs5aHfVbXC5eq1DM4d5RBEYbN2OqiJZG' },
    { grupo: 'Tríceps', titulo: 'Extensión de tríceps unilateral', id: '1K_QU1YffvcuzwmhrrsWS5dbjBrPSJIFA' },
    { grupo: 'Tríceps', titulo: 'Press francés con mancuernas', id: '1DWSVexMQiYkjHYTTMcFEhpRxpmgFFrye' },
    { grupo: 'Tríceps', titulo: 'Press francés con mancuernas en banco inclinado', id: '1aWfwf-hv0t-h6NW9xkb-3RR9-m2w1W0Q' },
    { grupo: 'Espalda', titulo: 'Jalón unilateral agarre neutro', id: '1oR58_IRjLuhFJA9Y-C3Mm-4K3bBwiIK1' },
    { grupo: 'Espalda', titulo: 'Jalón en dorsalera prono', id: '1TXkbZEJBwWekdCiVwZLcj1Xb0434HkLS' },
    { grupo: 'Espalda', titulo: 'Jalón en dorsalera agarre neutro', id: '1aJuJQ0y9XVlgnPlIWxCrsfmWQNWeMMpK' },
    { grupo: 'Espalda', titulo: 'Pull over con polea barra', id: '17wQK543G2UTVsHrIfuO2wnhi9zVx8ccR' },
    { grupo: 'Espalda', titulo: 'Pull over en polea soga', id: '1YBeCt9UwF80RYhNFNNsytD44LB6BjhXH' },
    { grupo: 'Espalda', titulo: 'Remo en polea agarre prono', id: '1gm-f1LWMWNoLjS7JAtCQUyGR34I0AZHG' },
    { grupo: 'Espalda', titulo: 'Remo Gironda neutro', id: '12byDyN3ASYpx2dyWCTNOYu3Dxne9-ZZx' },
    { grupo: 'Espalda', titulo: 'Remo prono con mancuernas', id: '1jE8qpTh1lwKFqoYZueXueJ9NnTiVmDWs' },
    { grupo: 'Espalda', titulo: 'Remo unilateral neutro en polea', id: '1hZ1ZqJCdtCB548oBUBcpY15Y1sjr_Mtk' },
    { grupo: 'Pecho', titulo: 'Cruces con polea alta', id: '1NgXJGzkjRNn-rn_EdVfxFQMwPteLOwVA' },
    { grupo: 'Pecho', titulo: 'Cruces con polea baja', id: '1dmFo_AKoBk9LPL-tmN29PyExRwJosQwd' },
    { grupo: 'Pecho', titulo: 'Fondos paralelas', id: '1RoakZvQc4DEERg-Rk78EiTJEmBwYTNup' },
    { grupo: 'Pecho', titulo: 'Pect deck', id: '1sYMlhKOOZZdZc4qABt5ywxXvQhYpepGj' },
    { grupo: 'Pecho', titulo: 'Press inclinado con mancuernas', id: '1Inz38000Wa_oKI9ovOB2X5SobloBPMT4' },
    { grupo: 'Pecho', titulo: 'Press plano con mancuernas', id: '1nAOrcg2VXFdfQ_plhsC7PDUS_kosp_VR' },
    { grupo: 'Pecho', titulo: 'Press plano Smith', id: '1p3kCU_cnvvNXwU-V_aUrCpGDQJL-EW5H' },
    { grupo: 'Running', titulo: 'Técnica de running', id: '1cR38DQeLNh0h7X0WGgueOL0AABqqGWp2' },
  ],

  comida: { kcal: 2200, macros: { P: 115, G: 60, C: 250 }, comidas: [
    { nombre: 'Desayuno', kcal: '~730 kcal · 4 opciones', opciones: [
      { nombre: 'Opción 1', kcal: 692, P: 34, G: 22, C: 98, items: ['2 claras de huevo + 2 huevos enteros', '82 g avena (peso crudo)', '1 banana (128 g)', '13 g mantequilla de maní'] },
      { nombre: 'Opción 2', kcal: 672, P: 52, G: 15, C: 80, items: ['190 g yogur natural descremado', '62 g avena (peso crudo)', '1 scoop proteína en polvo (30 g)', '1 banana (118 g)', '10 g mantequilla de maní'] },
      { nombre: 'Opción 3', kcal: 675, P: 35, G: 20, C: 83, items: ['130 g tostadas integrales', '3 claras de huevo + 2 huevos enteros', '1 manzana (152 g)', '12 g mantequilla de maní'] },
      { nombre: 'Opción 4', kcal: 677, P: 48, G: 20, C: 80, items: ['190 ml leche entera', '1 scoop proteína en polvo (30 g)', '65 g avena (peso crudo)', '1 banana (125 g)', '11 g mantequilla de maní'] },
    ] },
    { nombre: 'Almuerzo', kcal: '~750 kcal · 5 opciones', opciones: [
      { nombre: 'Opción 1', kcal: 750, P: 53, G: 16, C: 78, items: ['170 g pechuga de pollo (peso crudo)', '114 g arroz blanco (crudo · rinde ~319 g cocido)', 'Ensalada grande a gusto', '10 g aceite de oliva'] },
      { nombre: 'Opción 2', kcal: 700, P: 34, G: 12, C: 102, items: ['200 g merluza (peso crudo)', '145 g arroz blanco (crudo · rinde ~406 g cocido)', 'Verduras a gusto', '10 g aceite de oliva'] },
      { nombre: 'Opción 3', kcal: 700, P: 36, G: 24, C: 76, items: ['170 g carne magra (peso crudo)', '449 g papa (peso crudo)', '14 g arroz blanco (crudo)', 'Ensalada grande a gusto', '10 g aceite de oliva'] },
      { nombre: 'Opción 4', kcal: 700, P: 53, G: 16, C: 79, items: ['170 g pechuga de pollo (peso crudo)', '394 g batata (peso crudo)', '14 g arroz blanco (crudo)', 'Verduras a gusto', '10 g aceite de oliva'] },
      { nombre: 'Opción 5 · Wrap proteico', kcal: 769, P: 68, G: 25, C: 55, items: ['190 g pechuga de pollo (peso crudo · plancha o horno)', '80 g tortilla integral (1-2 tortillas grandes)', '85 g palta (media palta aprox.)', '38 g queso blanco descremado', '15 g arroz blanco (peso crudo · cocinar aparte)', 'Tomate y lechuga a gusto'] },
    ], nota: 'Intercambios proteína: 170 g pollo crudo = 190 g milanesa de pollo · 170 g carne cruda = 210 g milanesa.' },
    { nombre: 'Cena', kcal: '~750 kcal · 5 opciones', opciones: [
      { nombre: 'Opción 1', kcal: 699, P: 31, G: 12, C: 105, items: ['180 g merluza (peso crudo)', '150 g arroz blanco (crudo · rinde ~420 g cocido)', 'Ensalada a gusto', '10 g aceite de oliva'] },
      { nombre: 'Opción 2', kcal: 700, P: 50, G: 16, C: 83, items: ['160 g pechuga de pollo (peso crudo)', '412 g batata (peso crudo)', '15 g arroz blanco (crudo)', 'Verduras a gusto', '10 g aceite de oliva'] },
      { nombre: 'Opción 3', kcal: 753, P: 63, G: 19, C: 85, items: ['1 lata de atún al natural escurrida (140 g)', '2 huevos enteros', '60 g tostadas integrales', '88 g arroz blanco (crudo · rinde ~246 g cocido)'] },
      { nombre: 'Opción 4', kcal: 751, P: 34, G: 23, C: 81, items: ['160 g carne magra (peso crudo)', '119 g arroz blanco (crudo · rinde ~333 g cocido)', 'Ensalada a gusto', '10 g aceite de oliva'] },
      { nombre: 'Opción 5 · Ensalada de salmón', kcal: 750, P: 65, G: 32, C: 4, items: ['200 g salmón (peso crudo · horno o plancha)', '80 g palta (media palta aprox.)', '2 huevos enteros (duros o revueltos)', '8 g aceite de oliva', 'Lechuga, tomate, pepino a gusto'] },
    ] },
  ], reglas: [
    { titulo: 'Pesos crudos', texto: 'Todos los pesos son antes de cocinar. Arroz: 100 g crudo rinde ~280 g cocido. Pollo: 170 g crudo → ~128 g cocido. Merluza: 170 g crudo → ~136 g cocida.' },
    { titulo: 'Aceite', texto: 'Máximo 1 cucharada (12 g) por comida principal. No más de 2 cucharadas por día en total.' },
    { titulo: 'Verduras', texto: 'Libres en almuerzo y cena. Sin límite de cantidad.' },
    { titulo: 'Agua', texto: 'Mínimo 2,5 a 3 litros por día.' },
    { titulo: 'Cocción', texto: 'Horno, plancha, air fryer o vapor. Sin fritura.' },
    { titulo: 'Equivalencias', texto: '128 g pollo cocido = 143 g milanesa de pollo · 128 g carne cocida = 158 g milanesa.' },
  ] },

  tecnicas: [
    { nombre: 'BISERIE', texto: 'Dos ejercicios seguidos sin descanso. El descanso indicado va al terminar los dos.' },
    { nombre: 'SUPERSERIE', texto: 'Dos ejercicios de músculos opuestos seguidos sin descanso.' },
    { nombre: 'SERIE GIGANTE', texto: 'Tres o más ejercicios seguidos sin descanso con rest pause entre rondas.' },
    { nombre: 'DROPSET', texto: 'Llegás al fallo, bajás el peso 20-30% de inmediato y seguís sin descanso.' },
    { nombre: 'FALLO', texto: 'No podés completar ni una rep más con buena técnica. Sin trampa.' },
    { nombre: 'APROX', texto: 'Series de calentamiento con peso liviano. No cuentan como trabajo real.' },
  ],
};
