// Fuente: Plan_MarcoMeschini_v2.pdf (2026-09-16) y Alimentacion_MarcoMeschini.pdf (Agustín Paz, @aguspazfit). Mes 1.
// descanso en segundos (0 = sin descanso). aprox = series de aproximación (no cuentan). video = id de Google Drive (archivo en videos/<id>.mp4).
// cardio: pasos con seg (cuenta regresiva) o reps (botón "Hecho"); veces = repetir el paso; dosis = texto para mostrar.
const HIIT = { titulo: 'Cardio HIIT — post entrenamiento', sub: '3 vueltas · 1 min 30 seg de descanso entre vueltas', vueltas: 3, descansoVuelta: 90, pasos: [
  { nombre: 'Burpees', nota: 'Plancha completa, subís y saltás palmeando arriba.', dosis: '8 reps', reps: 8 },
  { nombre: 'Angelitos / jumping jacks', nota: 'Brazos y piernas coordinados. Ritmo máximo.', dosis: '40 seg', seg: 40 },
  { nombre: 'Sentadillas con salto', nota: 'Rodillas al pecho. Aterrizás suave y semiflexionado.', dosis: '20 reps', reps: 20 },
  { nombre: 'Mountain climbers', nota: 'Desde plancha alta. Rodillas al pecho alternando.', dosis: '30 seg', seg: 30 },
] };

window.DATA = {
  plan: { mes: 1, dias: [
    { id: 'lun', dia: 1, titulo: 'Torso + HIIT', bloques: [
      { aprox: 2, series: 3, reps: '10 - 8 - 6 subiendo el peso', descanso: 90, badges: ['APROX'],
        ejercicios: [{ nombre: 'Cruces con polea en banco 90° (emulando pect deck)', nota: '2 series de aproximación (5 y 3 reps) con peso ligero + 3 efectivas. El video muestra el pect deck: mismo movimiento.', video: '1sYMlhKOOZZdZc4qABt5ywxXvQhYpepGj' }] },
      { series: 4, reps: '20 - 15 - 12 - 10 subiendo el peso', descanso: 90, badges: [],
        ejercicios: [{ nombre: 'Pullover con polea soga', nota: 'Mantener 2 segundos abajo en cada repetición.', video: '1YBeCt9UwF80RYhNFNNsytD44LB6BjhXH' }] },
      { aprox: 2, series: 2, reps: '10 - 6 · dropset y fallo en la última', descanso: 120, badges: ['APROX', 'DROPSET', 'FALLO'],
        ejercicios: [{ nombre: 'Press inclinado con mancuernas', nota: '2 series de aproximación (5 y 3 reps) con peso ligero + 2 efectivas.', video: '1Inz38000Wa_oKI9ovOB2X5SobloBPMT4' }] },
      { series: 2, reps: '10 - 6 subiendo el peso', descanso: 90, badges: [],
        ejercicios: [{ nombre: 'Jalón en polea arrodillado agarre neutro unilateral', video: '1oR58_IRjLuhFJA9Y-C3Mm-4K3bBwiIK1' }] },
      { series: 2, reps: '10 - 6 subiendo el peso', descanso: 90, badges: [],
        ejercicios: [{ nombre: 'Press de hombros con mancuernas sentado', video: '1lFEraIA3AcWH9zHcrOq1A_JoTnjOUWLv' }] },
      { series: 3, reps: '15 - 10 - 8 en ambos, subiendo el peso', descanso: 90, badges: ['BISERIE'],
        ejercicios: [{ nombre: 'Press plano con mancuernas', video: '1nAOrcg2VXFdfQ_plhsC7PDUS_kosp_VR' }, { nombre: 'Curl de bíceps martillo en simultáneo con mancuernas', video: '1mUnTrondsdWRE0WXGyupH9yacUbqMjuK' }] },
      { series: 3, reps: '12 - 8 - 6 en ambos, subiendo el peso', descanso: 90, badges: ['BISERIE'],
        ejercicios: [{ nombre: 'Remo Gironda en polea', nota: 'Sentado en banco, pies adelante para trabar.', video: '12byDyN3ASYpx2dyWCTNOYu3Dxne9-ZZx' }, { nombre: 'Extensión de tríceps con polea barra', video: '1Y5wg7lrGj295FTbOIUZC1KI6fXK0iEXf' }] },
      { series: 2, reps: '15 - 10 en ambos · dropset y fallo en la última de ambos', descanso: 90, badges: ['BISERIE', 'DROPSET', 'FALLO'],
        ejercicios: [{ nombre: 'Extensión trasnuca con mancuerna a 2 manos' }, { nombre: 'Curl de bíceps con barra' }] },
    ], cardio: HIIT },

    { id: 'mar', dia: 2, titulo: 'Piernas + caminata', bloques: [
      { series: 3, reps: '20 - 15 - 12 subiendo el peso', descanso: 90, badges: [],
        ejercicios: [{ nombre: 'Sentadillas sumo con mancuerna' }] },
      { series: 2, reps: '15 - 10 en estocadas · 10 sentadillas con salto después de cada serie', descanso: 90, badges: ['BISERIE'],
        ejercicios: [{ nombre: 'Estocadas con mancuerna', nota: 'Una mano agarra la baranda.' }, { nombre: 'Sentadillas con salto', nota: '10 después de cada serie de estocadas.' }] },
      { series: 3, reps: '20 - 15 - 12 subiendo el peso · 2 reps antes del fallo', descanso: 90, badges: [],
        ejercicios: [{ nombre: 'Peso muerto rumano con mancuernas', nota: 'Quedarse 2 reps lejos del fallo en todas las series.' }] },
      { series: 3, reps: '20 - 15 - 12 subiendo el peso', descanso: 90, badges: [],
        ejercicios: [{ nombre: 'Sentadilla goblet con mancuerna', nota: 'Talones sobre discos. Puntas de pies hacia afuera.', video: '1GoMVCI0tXzHK-4EziKQa94jgZ2RTS8oX' }] },
      { series: 2, reps: '10 por pierna', descanso: 90, badges: [],
        ejercicios: [{ nombre: 'Estocadas con salto' }] },
    ], cardio: { titulo: 'Caminata en cinta — inclinación 10', sub: '20 minutos totales', pasos: [
      { nombre: 'Velocidad 5 km/h', nota: 'Ritmo suave de entrada. Inclinación 10%.', dosis: '5 min', seg: 300 },
      { nombre: 'Velocidad 6,5 km/h', nota: 'Ritmo moderado. Inclinación 10%.', dosis: '5 min', seg: 300 },
      { nombre: 'Velocidad 5 km/h', nota: 'Recuperación activa. Inclinación 10%.', dosis: '5 min', seg: 300 },
      { nombre: 'Velocidad 7 km/h', nota: 'Esfuerzo final. Inclinación 10%.', dosis: '5 min', seg: 300 },
    ] } },

    { id: 'mie', dia: 3, titulo: 'Torso + pasadas', bloques: [
      { series: 3, reps: '20 - 15 - 12 subiendo el peso', descanso: 90, badges: [],
        ejercicios: [{ nombre: 'Aperturas inclinadas con mancuernas', nota: 'No chocar las mancuernas en el medio para mantener tensión constante.' }] },
      { series: 3, reps: '20 - 15 - 12 subiendo el peso', descanso: 90, badges: [],
        ejercicios: [{ nombre: 'Vuelos posteriores con mancuernas sentado en banco' }] },
      { series: 3, reps: '15 - 10 - 8 subiendo el peso', descanso: 90, badges: [],
        ejercicios: [{ nombre: 'Press inclinado en Smith con banco inclinado' }] },
      { series: 2, reps: '15 - 10 subiendo el peso en remo · flexiones al fallo', descanso: 90, badges: ['BISERIE', 'FALLO'],
        ejercicios: [{ nombre: 'Remo con mancuerna agarre neutro' }, { nombre: 'Flexiones planas al fallo' }] },
      { series: 3, reps: '20 - 15 - 12 subiendo el peso', descanso: 90, badges: [],
        ejercicios: [{ nombre: 'Jalón en dorsalera agarre supino con barra', nota: 'Sentado en el piso.' }] },
      { series: 2, reps: '12 - 8 subiendo el peso · fondos al fallo', descanso: 90, badges: ['BISERIE', 'FALLO'],
        ejercicios: [{ nombre: 'Jalón arrodillado agarre prono con ambas poleas', nota: 'Sentado sobre los talones.', video: '1TXkbZEJBwWekdCiVwZLcj1Xb0434HkLS' }, { nombre: 'Fondos en banco para tríceps', nota: 'Al fallo.' }] },
      { series: 3, reps: '12 en vuelos · 20 - 15 - 12 en face pull, subiendo el peso en face pull', descanso: 90, badges: ['BISERIE'],
        ejercicios: [{ nombre: 'Vuelos laterales con polea', nota: '12 reps en cada serie.', video: '13OHlzX9n5FKteNVSbf8-4u4JIwWiEH-o' }, { nombre: 'Face pull con manoplas', video: '1Qlrzk2tdOYiYdVamqR04zC6TQexcbJ3L' }] },
      { series: 2, reps: '15 - 10 en ambos, subiendo el peso', descanso: 90, badges: ['BISERIE'],
        ejercicios: [{ nombre: 'Extensión de tríceps con polea soga', video: '1Rs5aHfVbXC5eq1DM4d5RBEYbN2OqiJZG' }, { nombre: 'Curl de bíceps martillo con soga', video: '1H2lcAYguaJuwVbkq9t8tGGF6PPLSs_RJ' }] },
      { series: 2, reps: 'Al fallo en curl · al fallo en vuelos alternos', descanso: 90, badges: ['BISERIE', 'FALLO'],
        ejercicios: [{ nombre: 'Curl de bíceps supino en simultáneo con mancuernas', nota: 'Sentado a 90°.', video: '1iUwLfPv09ZQb6fV0lX_EasJ4m-fk20Nz' }, { nombre: 'Vuelos laterales alternos con mancuernas', nota: 'Izquierda arriba → 5 reps → viceversa → ambos al fallo con poco peso.', video: '1m4QCfp_nzwroJp5KETYAO8_3I3-aNRge' }] },
      { series: 2, reps: '15 - 10 subiendo el peso', descanso: 90, badges: [],
        ejercicios: [{ nombre: 'Cruces con polea baja', nota: 'Altura de rodillas.', video: '1dmFo_AKoBk9LPL-tmN29PyExRwJosQwd' }] },
    ], cardio: { titulo: 'Pasadas en cinta', sub: '30 seg de descanso entre cada pasada', descansoPaso: 30, video: '1cR38DQeLNh0h7X0WGgueOL0AABqqGWp2', pasos: [
      { nombre: '7 km/h', nota: 'Activación suave.', dosis: '3 min', seg: 180 },
      { nombre: '8 km/h', nota: 'Ritmo sostenido.', dosis: '1:30 min', seg: 90 },
      { nombre: '10 km/h', nota: '30 seg de descanso entre cada una.', dosis: '40 seg ×2', seg: 40, veces: 2 },
      { nombre: '11 km/h', nota: '30 seg de descanso entre cada una.', dosis: '30 seg ×2', seg: 30, veces: 2 },
      { nombre: '12 km/h', nota: '30 seg de descanso entre cada una.', dosis: '30 seg ×2', seg: 30, veces: 2 },
      { nombre: '13 km/h', nota: '30 seg de descanso entre cada una.', dosis: '30 seg ×2', seg: 30, veces: 2 },
      { nombre: '14 km/h', nota: 'Dalo todo.', dosis: '30 seg', seg: 30 },
    ] } },

    { id: 'vie', dia: 5, titulo: 'Torso + HIIT', bloques: [
      { series: 3, reps: '15 - 10 - 8 · dropset y fallo en la última', descanso: 90, badges: ['DROPSET', 'FALLO'],
        ejercicios: [{ nombre: 'Press de hombros sentado en banco en Smith' }] },
      { series: 3, reps: '15 - 10 - 8 · dropset y fallo en la última', descanso: 90, badges: ['DROPSET', 'FALLO'],
        ejercicios: [{ nombre: 'Press plano en Smith', video: '1p3kCU_cnvvNXwU-V_aUrCpGDQJL-EW5H' }] },
      { series: 3, reps: '15 - 10 - 8 subiendo el peso', descanso: 90, badges: [],
        ejercicios: [{ nombre: 'Remo con barra agarre prono en Smith' }] },
      { series: 2, reps: 'Al fallo en ambos', descanso: 90, badges: ['BISERIE', 'FALLO'],
        ejercicios: [{ nombre: 'Jalón en poleas agarre neutro a dos manos sentado', video: '1aJuJQ0y9XVlgnPlIWxCrsfmWQNWeMMpK' }, { nombre: 'Extensión de tríceps con soga en polea', video: '1Rs5aHfVbXC5eq1DM4d5RBEYbN2OqiJZG' }] },
      { series: 2, reps: '15 - 10 en ambos, subiendo el peso', descanso: 90, badges: ['BISERIE'],
        ejercicios: [{ nombre: 'Curl de bíceps bayesian con poleas', nota: 'Codos detrás del cuerpo.' }, { nombre: 'Press plano con mancuernas', nota: 'Codos fijos, no se mueven.', video: '1nAOrcg2VXFdfQ_plhsC7PDUS_kosp_VR' }] },
      { series: 3, reps: '20 - 15 - 10 en ambos, subiendo el peso', descanso: 90, badges: ['BISERIE'],
        ejercicios: [{ nombre: 'Cruces con polea alta arrodillado', video: '1NgXJGzkjRNn-rn_EdVfxFQMwPteLOwVA' }, { nombre: 'Curl Scott en banco inclinado unilateral', nota: 'Codo delante del cuerpo.' }] },
      { series: 3, reps: '20 - 15 - 12 en ambos, subiendo el peso', descanso: 90, badges: ['BISERIE'],
        ejercicios: [{ nombre: 'Vuelos laterales con mancuernas', video: '19bX9TLAWEd6avohJQVJyLLNqlSiRp81p' }, { nombre: 'Face pull con soga', video: '1Qlrzk2tdOYiYdVamqR04zC6TQexcbJ3L' }] },
      { series: 3, reps: '20 - 15 - 12 en ambos, subiendo el peso', descanso: 90, badges: ['BISERIE'],
        ejercicios: [{ nombre: 'Pullover con polea barra', video: '17wQK543G2UTVsHrIfuO2wnhi9zVx8ccR' }, { nombre: 'Extensión trasnuca con polea soga', video: '1bsgBx3qN-tfK_VnNDwXMhn5q8XMV__ZU' }] },
    ], cardio: HIIT },
  ] },

  videos: [
    { grupo: 'Abdominales', titulo: 'Crunch abdominal con piernas elevadas', id: '12SzEuicNeXrrQdkijze-KNy8HSWyTt3g' },
    { grupo: 'Abdominales', titulo: 'Crunch abdominal declinado', id: '1xM4enzGVqvyV2BCBy5TI6YJc2PzX2MGM' },
    { grupo: 'Abdominales', titulo: 'Crunch abdominal con piernas elevadas y disco', id: '1b5J2EbcthvXN7O6mYS6_LU24fEDhwb44' },
    { grupo: 'Abdominales', titulo: 'Elevación de piernas acostado', id: '1yN-mJJOazUtodL6QuKMAN7_dS8UXe9aU' },
    { grupo: 'Bíceps', titulo: 'Curl de bíceps inclinado', id: '1LJ15BBVzDlk4gMozdUR6UwHM9JixFz7W' },
    { grupo: 'Bíceps', titulo: 'Curl de bíceps martillo', id: '1mUnTrondsdWRE0WXGyupH9yacUbqMjuK' },
    { grupo: 'Bíceps', titulo: 'Curl de bíceps martillo unilateral en polea', id: '1H2lcAYguaJuwVbkq9t8tGGF6PPLSs_RJ' },
    { grupo: 'Bíceps', titulo: 'Curl de bíceps supino con alternación', id: '1L7aDg4RhcqPQEcmkfafkJ192Wv60uLGA' },
    { grupo: 'Bíceps', titulo: 'Curl de bíceps supino con polea', id: '1FuIr0YTlL0mRv9NrkZAZnIYtCBu7TaMp' },
    { grupo: 'Bíceps', titulo: 'Curl de bíceps supino sentado', id: '1iUwLfPv09ZQb6fV0lX_EasJ4m-fk20Nz' },
    { grupo: 'Hombros', titulo: 'Face pull', id: '1Qlrzk2tdOYiYdVamqR04zC6TQexcbJ3L' },
    { grupo: 'Hombros', titulo: 'Press de hombros con mancuernas', id: '1lFEraIA3AcWH9zHcrOq1A_JoTnjOUWLv' },
    { grupo: 'Hombros', titulo: 'Vuelos isométricos alternos', id: '1m4QCfp_nzwroJp5KETYAO8_3I3-aNRge' },
    { grupo: 'Hombros', titulo: 'Vuelos laterales con mancuernas', id: '19bX9TLAWEd6avohJQVJyLLNqlSiRp81p' },
    { grupo: 'Hombros', titulo: 'Vuelos laterales unilateral en polea', id: '13OHlzX9n5FKteNVSbf8-4u4JIwWiEH-o' },
    { grupo: 'Hombros', titulo: 'Vuelos posteriores con polea', id: '1uAoMJ9ahx5q_v5uLnl2BqS7FIOqrZa1s' },
    { grupo: 'Hombros', titulo: 'Vuelos posteriores en pect deck', id: '1E809RsvQoE6gSJDHEdwrihya_aBQs5ne' },
    { grupo: 'Piernas', titulo: 'Aductor en máquina', id: '1_X4IP_s7HObZ3BM_x9RgxaVxGBllVsCS' },
    { grupo: 'Piernas', titulo: 'Curl femoral en máquina', id: '1YZ9t3shIZrHE1evZAtlVPJ9nCelbjT6m' },
    { grupo: 'Piernas', titulo: 'Extensión de cuádriceps', id: '18vYJAYCpYwRl8sUU-8PYzKGQmi-2LMD9' },
    { grupo: 'Piernas', titulo: 'Goblet squat', id: '1GoMVCI0tXzHK-4EziKQa94jgZ2RTS8oX' },
    { grupo: 'Piernas', titulo: 'Hack squat', id: '1xEqhjRlS7zmNVUg8c3uhntvB8sHq_LK_' },
    { grupo: 'Piernas', titulo: 'Prensa', id: '1ULzO9uPU7EtOR0L9WY7-lN-Ri28qPgc1' },
    { grupo: 'Piernas', titulo: 'Sentadilla en Smith', id: '1WQr-FBtumZg8QLTtn8xT5PNp6yXN-QU8' },
    { grupo: 'Tríceps', titulo: 'Extensión de tríceps en polea barra', id: '1Y5wg7lrGj295FTbOIUZC1KI6fXK0iEXf' },
    { grupo: 'Tríceps', titulo: 'Extensión trasnuca en polea soga', id: '1bsgBx3qN-tfK_VnNDwXMhn5q8XMV__ZU' },
    { grupo: 'Tríceps', titulo: 'Extensión de tríceps soga', id: '1Rs5aHfVbXC5eq1DM4d5RBEYbN2OqiJZG' },
    { grupo: 'Tríceps', titulo: 'Extensión de tríceps unilateral', id: '1K_QU1YffvcuzwmhrrsWS5dbjBrPSJIFA' },
    { grupo: 'Tríceps', titulo: 'Press francés con mancuernas', id: '1DWSVexMQiYkjHYTTMcFEhpRxpmgFFrye' },
    { grupo: 'Tríceps', titulo: 'Press francés con mancuernas en banco inclinado', id: '1aWfwf-hv0t-h6NW9xkb-3RR9-m2w1W0Q' },
    { grupo: 'Espalda', titulo: 'Jalón unilateral agarre neutro', id: '1oR58_IRjLuhFJA9Y-C3Mm-4K3bBwiIK1' },
    { grupo: 'Espalda', titulo: 'Jalón en dorsalera prono', id: '1TXkbZEJBwWekdCiVwZLcj1Xb0434HkLS' },
    { grupo: 'Espalda', titulo: 'Jalón en dorsalera agarre neutro', id: '1aJuJQ0y9XVlgnPlIWxCrsfmWQNWeMMpK' },
    { grupo: 'Espalda', titulo: 'Pull over con polea barra', id: '17wQK543G2UTVsHrIfuO2wnhi9zVx8ccR' },
    { grupo: 'Espalda', titulo: 'Pull over en polea soga', id: '1YBeCt9UwF80RYhNFNNsytD44LB6BjhXH' },
    { grupo: 'Espalda', titulo: 'Remo en polea agarre prono', id: '1gm-f1LWMWNoLjS7JAtCQUyGR34I0AZHG' },
    { grupo: 'Espalda', titulo: 'Remo Gironda neutro', id: '12byDyN3ASYpx2dyWCTNOYu3Dxne9-ZZx' },
    { grupo: 'Espalda', titulo: 'Remo prono con mancuernas', id: '1jE8qpTh1lwKFqoYZueXueJ9NnTiVmDWs' },
    { grupo: 'Espalda', titulo: 'Remo unilateral neutro en polea', id: '1hZ1ZqJCdtCB548oBUBcpY15Y1sjr_Mtk' },
    { grupo: 'Pecho', titulo: 'Cruces con polea alta', id: '1NgXJGzkjRNn-rn_EdVfxFQMwPteLOwVA' },
    { grupo: 'Pecho', titulo: 'Cruces con polea baja', id: '1dmFo_AKoBk9LPL-tmN29PyExRwJosQwd' },
    { grupo: 'Pecho', titulo: 'Fondos paralelas', id: '1RoakZvQc4DEERg-Rk78EiTJEmBwYTNup' },
    { grupo: 'Pecho', titulo: 'Pect deck', id: '1sYMlhKOOZZdZc4qABt5ywxXvQhYpepGj' },
    { grupo: 'Pecho', titulo: 'Press inclinado con mancuernas', id: '1Inz38000Wa_oKI9ovOB2X5SobloBPMT4' },
    { grupo: 'Pecho', titulo: 'Press plano con mancuernas', id: '1nAOrcg2VXFdfQ_plhsC7PDUS_kosp_VR' },
    { grupo: 'Pecho', titulo: 'Press plano Smith', id: '1p3kCU_cnvvNXwU-V_aUrCpGDQJL-EW5H' },
    { grupo: 'Running', titulo: 'Técnica de running', id: '1cR38DQeLNh0h7X0WGgueOL0AABqqGWp2' },
  ],

  comida: { kcal: 2200, macros: { P: 115, G: 60, C: 250 }, comidas: [
    { nombre: 'Desayuno', kcal: '~730 kcal · 4 opciones', opciones: [
      { nombre: 'Opción 1', kcal: 692, P: 34, G: 22, C: 98, items: ['2 claras de huevo + 2 huevos enteros', '82 g avena (peso crudo)', '1 banana (128 g)', '13 g mantequilla de maní'] },
      { nombre: 'Opción 2', kcal: 672, P: 52, G: 15, C: 80, items: ['190 g yogur natural descremado', '62 g avena (peso crudo)', '1 scoop proteína en polvo (30 g)', '1 banana (118 g)', '10 g mantequilla de maní'] },
      { nombre: 'Opción 3', kcal: 675, P: 35, G: 20, C: 83, items: ['130 g tostadas integrales', '3 claras de huevo + 2 huevos enteros', '1 manzana (152 g)', '12 g mantequilla de maní'] },
      { nombre: 'Opción 4', kcal: 677, P: 48, G: 20, C: 80, items: ['190 ml leche entera', '1 scoop proteína en polvo (30 g)', '65 g avena (peso crudo)', '1 banana (125 g)', '11 g mantequilla de maní'] },
    ] },
    { nombre: 'Almuerzo', kcal: '~750 kcal · 5 opciones', opciones: [
      { nombre: 'Opción 1', kcal: 750, P: 53, G: 16, C: 78, items: ['170 g pechuga de pollo (peso crudo)', '114 g arroz blanco (crudo · rinde ~319 g cocido)', 'Ensalada grande a gusto', '10 g aceite de oliva'] },
      { nombre: 'Opción 2', kcal: 700, P: 34, G: 12, C: 102, items: ['200 g merluza (peso crudo)', '145 g arroz blanco (crudo · rinde ~406 g cocido)', 'Verduras a gusto', '10 g aceite de oliva'] },
      { nombre: 'Opción 3', kcal: 700, P: 36, G: 24, C: 76, items: ['170 g carne magra (peso crudo)', '449 g papa (peso crudo)', '14 g arroz blanco (crudo)', 'Ensalada grande a gusto', '10 g aceite de oliva'] },
      { nombre: 'Opción 4', kcal: 700, P: 53, G: 16, C: 79, items: ['170 g pechuga de pollo (peso crudo)', '394 g batata (peso crudo)', '14 g arroz blanco (crudo)', 'Verduras a gusto', '10 g aceite de oliva'] },
      { nombre: 'Opción 5 · Wrap proteico', kcal: 769, P: 68, G: 25, C: 55, items: ['190 g pechuga de pollo (peso crudo · plancha o horno)', '80 g tortilla integral (1-2 tortillas grandes)', '85 g palta (media palta aprox.)', '38 g queso blanco descremado', '15 g arroz blanco (peso crudo · cocinar aparte)', 'Tomate y lechuga a gusto'] },
    ], nota: 'Intercambios proteína: 170 g pollo crudo = 190 g milanesa de pollo · 170 g carne cruda = 210 g milanesa.' },
    { nombre: 'Cena', kcal: '~750 kcal · 5 opciones', opciones: [
      { nombre: 'Opción 1', kcal: 699, P: 31, G: 12, C: 105, items: ['180 g merluza (peso crudo)', '150 g arroz blanco (crudo · rinde ~420 g cocido)', 'Ensalada a gusto', '10 g aceite de oliva'] },
      { nombre: 'Opción 2', kcal: 700, P: 50, G: 16, C: 83, items: ['160 g pechuga de pollo (peso crudo)', '412 g batata (peso crudo)', '15 g arroz blanco (crudo)', 'Verduras a gusto', '10 g aceite de oliva'] },
      { nombre: 'Opción 3', kcal: 753, P: 63, G: 19, C: 85, items: ['1 lata de atún al natural escurrida (140 g)', '2 huevos enteros', '60 g tostadas integrales', '88 g arroz blanco (crudo · rinde ~246 g cocido)'] },
      { nombre: 'Opción 4', kcal: 751, P: 34, G: 23, C: 81, items: ['160 g carne magra (peso crudo)', '119 g arroz blanco (crudo · rinde ~333 g cocido)', 'Ensalada a gusto', '10 g aceite de oliva'] },
      { nombre: 'Opción 5 · Ensalada de salmón', kcal: 750, P: 65, G: 32, C: 4, items: ['200 g salmón (peso crudo · horno o plancha)', '80 g palta (media palta aprox.)', '2 huevos enteros (duros o revueltos)', '8 g aceite de oliva', 'Lechuga, tomate, pepino a gusto'] },
    ] },
  ], reglas: [
    { titulo: 'Pesos crudos', texto: 'Todos los pesos son antes de cocinar. Arroz: 100 g crudo rinde ~280 g cocido. Pollo: 170 g crudo → ~128 g cocido. Merluza: 170 g crudo → ~136 g cocida.' },
    { titulo: 'Aceite', texto: 'Máximo 1 cucharada (12 g) por comida principal. No más de 2 cucharadas por día en total.' },
    { titulo: 'Verduras', texto: 'Libres en almuerzo y cena. Sin límite de cantidad.' },
    { titulo: 'Agua', texto: 'Mínimo 2,5 a 3 litros por día.' },
    { titulo: 'Cocción', texto: 'Horno, plancha, air fryer o vapor. Sin fritura.' },
    { titulo: 'Equivalencias', texto: '128 g pollo cocido = 143 g milanesa de pollo · 128 g carne cocida = 158 g milanesa.' },
  ] },

  tecnicas: [
    { nombre: 'BISERIE', texto: 'Dos ejercicios seguidos sin descanso. El descanso indicado va al terminar los dos.' },
    { nombre: 'DROPSET', texto: 'Llegás al fallo, bajás el peso 20-30% de inmediato y seguís sin descanso.' },
    { nombre: 'FALLO', texto: 'No podés completar ni una rep más con buena técnica. Sin trampa ni impulso.' },
    { nombre: 'APROX', texto: 'Series de aproximación: calentamiento progresivo buscando el peso de trabajo.' },
  ],
};
